### ISSUE TITLE
Reco Pc Server not working

### ISSUE THREAD

**Issue by AbdobiZark** [Arvinth-Krishna/Reco-PC-Server#19]
>Connect button not responding
>Offline bot
![image](https://user-images.githubusercontent.com/88251043/163222077-ee166f20-b48e-41d5-9e35-06065e86f7c1.png)

-Already meet the requirements (using latest)
-Using Python 3.10
-Tutorial used: https://www.youtube.com/watch?v=HbqW0zCIZYg
-Reinstall 3x & Kick 3x
![image](https://user-images.githubusercontent.com/88251043/163221284-7c93b004-4201-47b9-b747-59bbe70e940e.png)
![image](https://user-images.githubusercontent.com/88251043/163221525-12ff858d-7cf8-4df0-b4b0-c868046a7b55.png)

**Comment by Arvinth-Krishna** [comment]
Did u enter bot token in your env file?

And also please make sure that u have enabled the switches in ur Discord Developer portal.
https://user-images.githubusercontent.com/49812701/149883812-53643ba8-df84-47ee-89e5-cf3177202b7f.png

**Comment by AbdobiZark** [comment]
> Did u enter bot token in your env file?
> 
> And also please make sure that u have enabled the switches in ur Discord Developer portal. https://user-images.githubusercontent.com/49812701/149883812-53643ba8-df84-47ee-89e5-cf3177202b7f.png

Thanks all good now
