### ISSUE TITLE
when i press connect it doesnt open the links

### ISSUE THREAD

**Issue by Soullover123** [Arvinth-Krishna/Reco-PC-Server#33]
when i look into the terminal and code there are many unknown modules which causes failure of the connection

**Comment by Arvinth-Krishna** [comment]
Download the repo directly (Not from Releases).
Then make sure all step has been followed: https://github.com/Arvinth-Krishna/Reco-PC-Server#text-instructions

**Comment by Soullover123** [comment]
I tried and it didnt work, when i run it in VS code this is the error i see :
  colorforCommonMsg=int(configs.EMBEDS_COLOR,0)
TypeError: int() can't convert non-string with explicit base

**Comment by Arvinth-Krishna** [comment]
Did u change anything in the env file other than adding a bot token?

**Comment by Soullover123** [comment]
no

**Comment by Soullover123** [comment]
i looked through every requirement and installed them and checked them manually and i checked if i had the correct python version which i did

**Comment by Arvinth-Krishna** [comment]
Please reopen the issue if you still have it.
