### ISSUE TITLE
Things to add to Reco!

### ISSUE THREAD

**Issue by BigFlubba** [Arvinth-Krishna/Reco-PC-Server#8]
-all media is commands have a duration feature !media vol-down 5 10m
-!media now playing, seek, pause at end of track
-add embeds to all outputs
-update read.me for easier to understand for non advanced users and list of all commands and usages
-auto update (or at least a program to notify when a new version or reco is available (with link to auto download the new version))
-update mobile app for cleaner look and all new functions integrated and more
-show current CPU, RAM, GPU, Disk, Network usage
> usage over time with a graph
> app list with given usages (sortable)

**Comment by Arvinth-Krishna** [comment]
✅ all media is commands have a duration feature !media vol-down 5 10m
❌ !media now playing, seek, pause at end of track
✅ add embeds to all outputs
✅ update read.me for easier to understand for non advanced users and list of all commands and usages
✅ auto update (or at least a program to notify when a new version or reco is available (with link to auto download the new version))
❌ update the mobile app for a cleaner look and all-new functions integrated and more.
❌ show current CPU, RAM, GPU, Disk & Network usage.

**Comment by TheHunter1234** [comment]
Epic progress so far. Can't wait to give it a spin. Maybe I'll ha e to think harder for things to add to the list. Lol.

**Comment by BigFlubba** [comment]
-add auto status (bot status' (idle, online, dnd) changes according if the pc is active or idle (screensaver active or display onn))

**Comment by BigFlubba** [comment]
-add !commands feature to display all the commands available instead of having to use !reco for a more simple experience

**Comment by BigFlubba** [comment]
-add !uptime command to display bots current uptime connected to the internet without interruptions
resets on internet disconnect and PC sleep or power off

**Comment by BigFlubba** [comment]
integration with [RPC-Pc-Status](https://github.com/Faelayis/RPC-Pc-Status) for bot status

**Comment by BigFlubba** [comment]
-option for bot online message to send in channels of choosing

**Comment by Arvinth-Krishna** [comment]
Started **Things to add to Reco!** in Discussion : https://github.com/Arvinth-Krishna/Reco-PC-Server/discussions/12#discussion-3833117
